export default {
  locale: 'en',
  messages: {
    siteTitle: 'The Sales Journal Online',
    addUser: 'Add User',
    addEntry: 'Add Entry',
    twitterMessage: 'We are on Twitter',
    submit: 'Submit',
    email: 'Email',
    password: 'Password',
    verifyPassword: 'Verify Password',
    register: 'Register',
    homePageTitle: 'Improve Your Sales',
    login: 'Log In',
    delete: 'Delete',
    save: 'Save',
    logout: 'Log Out',
    learnMore: 'Learn More',
    entries: 'View Entries',
    sendResetEmail: 'Send password reset email',
    forgotPasswordTitle: 'Request password reset',
    resetPasswordTitle: 'Reset your password',
    resetPassword: 'Reset password',
    userList: 'User List',
    quoteList: 'Quote List',
    admin: 'Admin',
  },
};
